/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CollectionOfMemberActivityEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionOfMemberActivityEvents{}

// CollectionOfMemberActivityEvents The last 50 Goal events for a member on a specific list.
type CollectionOfMemberActivityEvents struct {
	// The last 50 Goal events triggered by a member.
	Goals []Goal `json:"goals,omitempty"`
	// The list id.
	ListId *string `json:"list_id,omitempty"`
	// The MD5 hash of the lowercase version of the list member's email address.
	EmailId *string `json:"email_id,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems *int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}

// NewCollectionOfMemberActivityEvents instantiates a new CollectionOfMemberActivityEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionOfMemberActivityEvents() *CollectionOfMemberActivityEvents {
	this := CollectionOfMemberActivityEvents{}
	return &this
}

// NewCollectionOfMemberActivityEventsWithDefaults instantiates a new CollectionOfMemberActivityEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionOfMemberActivityEventsWithDefaults() *CollectionOfMemberActivityEvents {
	this := CollectionOfMemberActivityEvents{}
	return &this
}

// GetGoals returns the Goals field value if set, zero value otherwise.
func (o *CollectionOfMemberActivityEvents) GetGoals() []Goal {
	if o == nil || IsNil(o.Goals) {
		var ret []Goal
		return ret
	}
	return o.Goals
}

// GetGoalsOk returns a tuple with the Goals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfMemberActivityEvents) GetGoalsOk() ([]Goal, bool) {
	if o == nil || IsNil(o.Goals) {
		return nil, false
	}
	return o.Goals, true
}

// HasGoals returns a boolean if a field has been set.
func (o *CollectionOfMemberActivityEvents) HasGoals() bool {
	if o != nil && !IsNil(o.Goals) {
		return true
	}

	return false
}

// SetGoals gets a reference to the given []Goal and assigns it to the Goals field.
func (o *CollectionOfMemberActivityEvents) SetGoals(v []Goal) {
	o.Goals = v
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *CollectionOfMemberActivityEvents) GetListId() string {
	if o == nil || IsNil(o.ListId) {
		var ret string
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfMemberActivityEvents) GetListIdOk() (*string, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *CollectionOfMemberActivityEvents) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given string and assigns it to the ListId field.
func (o *CollectionOfMemberActivityEvents) SetListId(v string) {
	o.ListId = &v
}

// GetEmailId returns the EmailId field value if set, zero value otherwise.
func (o *CollectionOfMemberActivityEvents) GetEmailId() string {
	if o == nil || IsNil(o.EmailId) {
		var ret string
		return ret
	}
	return *o.EmailId
}

// GetEmailIdOk returns a tuple with the EmailId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfMemberActivityEvents) GetEmailIdOk() (*string, bool) {
	if o == nil || IsNil(o.EmailId) {
		return nil, false
	}
	return o.EmailId, true
}

// HasEmailId returns a boolean if a field has been set.
func (o *CollectionOfMemberActivityEvents) HasEmailId() bool {
	if o != nil && !IsNil(o.EmailId) {
		return true
	}

	return false
}

// SetEmailId gets a reference to the given string and assigns it to the EmailId field.
func (o *CollectionOfMemberActivityEvents) SetEmailId(v string) {
	o.EmailId = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *CollectionOfMemberActivityEvents) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfMemberActivityEvents) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *CollectionOfMemberActivityEvents) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *CollectionOfMemberActivityEvents) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CollectionOfMemberActivityEvents) GetLinks() []ResourceLink {
	if o == nil || IsNil(o.Links) {
		var ret []ResourceLink
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfMemberActivityEvents) GetLinksOk() ([]ResourceLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CollectionOfMemberActivityEvents) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []ResourceLink and assigns it to the Links field.
func (o *CollectionOfMemberActivityEvents) SetLinks(v []ResourceLink) {
	o.Links = v
}

func (o CollectionOfMemberActivityEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionOfMemberActivityEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Goals) {
		toSerialize["goals"] = o.Goals
	}
	if !IsNil(o.ListId) {
		toSerialize["list_id"] = o.ListId
	}
	if !IsNil(o.EmailId) {
		toSerialize["email_id"] = o.EmailId
	}
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCollectionOfMemberActivityEvents struct {
	value *CollectionOfMemberActivityEvents
	isSet bool
}

func (v NullableCollectionOfMemberActivityEvents) Get() *CollectionOfMemberActivityEvents {
	return v.value
}

func (v *NullableCollectionOfMemberActivityEvents) Set(val *CollectionOfMemberActivityEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionOfMemberActivityEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionOfMemberActivityEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionOfMemberActivityEvents(val *CollectionOfMemberActivityEvents) *NullableCollectionOfMemberActivityEvents {
	return &NullableCollectionOfMemberActivityEvents{value: val, isSet: true}
}

func (v NullableCollectionOfMemberActivityEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionOfMemberActivityEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


