/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DomainPerformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainPerformance{}

// DomainPerformance Statistics for the top-performing email domains in a campaign.
type DomainPerformance struct {
	// The top 5 email domains based on total delivered emails.
	Domains []EmailDomain `json:"domains,omitempty"`
	// The total number of emails sent for the campaign.
	TotalSent *int32 `json:"total_sent,omitempty"`
	// The unique id for the campaign.
	CampaignId *string `json:"campaign_id,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems *int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}

// NewDomainPerformance instantiates a new DomainPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainPerformance() *DomainPerformance {
	this := DomainPerformance{}
	return &this
}

// NewDomainPerformanceWithDefaults instantiates a new DomainPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainPerformanceWithDefaults() *DomainPerformance {
	this := DomainPerformance{}
	return &this
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *DomainPerformance) GetDomains() []EmailDomain {
	if o == nil || IsNil(o.Domains) {
		var ret []EmailDomain
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainPerformance) GetDomainsOk() ([]EmailDomain, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *DomainPerformance) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []EmailDomain and assigns it to the Domains field.
func (o *DomainPerformance) SetDomains(v []EmailDomain) {
	o.Domains = v
}

// GetTotalSent returns the TotalSent field value if set, zero value otherwise.
func (o *DomainPerformance) GetTotalSent() int32 {
	if o == nil || IsNil(o.TotalSent) {
		var ret int32
		return ret
	}
	return *o.TotalSent
}

// GetTotalSentOk returns a tuple with the TotalSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainPerformance) GetTotalSentOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSent) {
		return nil, false
	}
	return o.TotalSent, true
}

// HasTotalSent returns a boolean if a field has been set.
func (o *DomainPerformance) HasTotalSent() bool {
	if o != nil && !IsNil(o.TotalSent) {
		return true
	}

	return false
}

// SetTotalSent gets a reference to the given int32 and assigns it to the TotalSent field.
func (o *DomainPerformance) SetTotalSent(v int32) {
	o.TotalSent = &v
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *DomainPerformance) GetCampaignId() string {
	if o == nil || IsNil(o.CampaignId) {
		var ret string
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainPerformance) GetCampaignIdOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignId) {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *DomainPerformance) HasCampaignId() bool {
	if o != nil && !IsNil(o.CampaignId) {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *DomainPerformance) SetCampaignId(v string) {
	o.CampaignId = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *DomainPerformance) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainPerformance) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *DomainPerformance) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *DomainPerformance) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *DomainPerformance) GetLinks() []ResourceLink {
	if o == nil || IsNil(o.Links) {
		var ret []ResourceLink
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainPerformance) GetLinksOk() ([]ResourceLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *DomainPerformance) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []ResourceLink and assigns it to the Links field.
func (o *DomainPerformance) SetLinks(v []ResourceLink) {
	o.Links = v
}

func (o DomainPerformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainPerformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.TotalSent) {
		toSerialize["total_sent"] = o.TotalSent
	}
	if !IsNil(o.CampaignId) {
		toSerialize["campaign_id"] = o.CampaignId
	}
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableDomainPerformance struct {
	value *DomainPerformance
	isSet bool
}

func (v NullableDomainPerformance) Get() *DomainPerformance {
	return v.value
}

func (v *NullableDomainPerformance) Set(val *DomainPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainPerformance(val *DomainPerformance) *NullableDomainPerformance {
	return &NullableDomainPerformance{value: val, isSet: true}
}

func (v NullableDomainPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


