/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity{}

// GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity struct for GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity
type GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity struct {
	Clicks []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner `json:"clicks,omitempty"`
	Impressions []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner `json:"impressions,omitempty"`
	Revenue []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner `json:"revenue,omitempty"`
}

// NewGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity instantiates a new GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity() *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity {
	this := GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity{}
	return &this
}

// NewGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityWithDefaults instantiates a new GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityWithDefaults() *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity {
	this := GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity{}
	return &this
}

// GetClicks returns the Clicks field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetClicks() []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner {
	if o == nil || IsNil(o.Clicks) {
		var ret []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner
		return ret
	}
	return o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetClicksOk() ([]GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner, bool) {
	if o == nil || IsNil(o.Clicks) {
		return nil, false
	}
	return o.Clicks, true
}

// HasClicks returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) HasClicks() bool {
	if o != nil && !IsNil(o.Clicks) {
		return true
	}

	return false
}

// SetClicks gets a reference to the given []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner and assigns it to the Clicks field.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) SetClicks(v []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityClicksInner) {
	o.Clicks = v
}

// GetImpressions returns the Impressions field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetImpressions() []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner {
	if o == nil || IsNil(o.Impressions) {
		var ret []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner
		return ret
	}
	return o.Impressions
}

// GetImpressionsOk returns a tuple with the Impressions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetImpressionsOk() ([]GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner, bool) {
	if o == nil || IsNil(o.Impressions) {
		return nil, false
	}
	return o.Impressions, true
}

// HasImpressions returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) HasImpressions() bool {
	if o != nil && !IsNil(o.Impressions) {
		return true
	}

	return false
}

// SetImpressions gets a reference to the given []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner and assigns it to the Impressions field.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) SetImpressions(v []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityImpressionsInner) {
	o.Impressions = v
}

// GetRevenue returns the Revenue field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetRevenue() []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner {
	if o == nil || IsNil(o.Revenue) {
		var ret []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner
		return ret
	}
	return o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) GetRevenueOk() ([]GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner, bool) {
	if o == nil || IsNil(o.Revenue) {
		return nil, false
	}
	return o.Revenue, true
}

// HasRevenue returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) HasRevenue() bool {
	if o != nil && !IsNil(o.Revenue) {
		return true
	}

	return false
}

// SetRevenue gets a reference to the given []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner and assigns it to the Revenue field.
func (o *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) SetRevenue(v []GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivityRevenueInner) {
	o.Revenue = v
}

func (o GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Clicks) {
		toSerialize["clicks"] = o.Clicks
	}
	if !IsNil(o.Impressions) {
		toSerialize["impressions"] = o.Impressions
	}
	if !IsNil(o.Revenue) {
		toSerialize["revenue"] = o.Revenue
	}
	return toSerialize, nil
}

type NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity struct {
	value *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity
	isSet bool
}

func (v NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) Get() *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity {
	return v.value
}

func (v *NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) Set(val *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity(val *GetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) *NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity {
	return &NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity{value: val, isSet: true}
}

func (v NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReportingFacebookAds200ResponseFacebookAdsInnerAllOfAudienceActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


