/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations{}

// GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations struct for GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations
type GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations struct {
	Countries []string `json:"countries,omitempty"`
	Regions []string `json:"regions,omitempty"`
	Cities []string `json:"cities,omitempty"`
	Zips []string `json:"zips,omitempty"`
}

// NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations instantiates a new GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations {
	this := GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations{}
	return &this
}

// NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocationsWithDefaults instantiates a new GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocationsWithDefaults() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations {
	this := GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations{}
	return &this
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetCountries() []string {
	if o == nil || IsNil(o.Countries) {
		var ret []string
		return ret
	}
	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Countries) {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) HasCountries() bool {
	if o != nil && !IsNil(o.Countries) {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []string and assigns it to the Countries field.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) SetCountries(v []string) {
	o.Countries = v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetRegions() []string {
	if o == nil || IsNil(o.Regions) {
		var ret []string
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetRegionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []string and assigns it to the Regions field.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) SetRegions(v []string) {
	o.Regions = v
}

// GetCities returns the Cities field value if set, zero value otherwise.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetCities() []string {
	if o == nil || IsNil(o.Cities) {
		var ret []string
		return ret
	}
	return o.Cities
}

// GetCitiesOk returns a tuple with the Cities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetCitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Cities) {
		return nil, false
	}
	return o.Cities, true
}

// HasCities returns a boolean if a field has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) HasCities() bool {
	if o != nil && !IsNil(o.Cities) {
		return true
	}

	return false
}

// SetCities gets a reference to the given []string and assigns it to the Cities field.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) SetCities(v []string) {
	o.Cities = v
}

// GetZips returns the Zips field value if set, zero value otherwise.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetZips() []string {
	if o == nil || IsNil(o.Zips) {
		var ret []string
		return ret
	}
	return o.Zips
}

// GetZipsOk returns a tuple with the Zips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) GetZipsOk() ([]string, bool) {
	if o == nil || IsNil(o.Zips) {
		return nil, false
	}
	return o.Zips, true
}

// HasZips returns a boolean if a field has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) HasZips() bool {
	if o != nil && !IsNil(o.Zips) {
		return true
	}

	return false
}

// SetZips gets a reference to the given []string and assigns it to the Zips field.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) SetZips(v []string) {
	o.Zips = v
}

func (o GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Countries) {
		toSerialize["countries"] = o.Countries
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	if !IsNil(o.Cities) {
		toSerialize["cities"] = o.Cities
	}
	if !IsNil(o.Zips) {
		toSerialize["zips"] = o.Zips
	}
	return toSerialize, nil
}

type NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations struct {
	value *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations
	isSet bool
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) Get() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations {
	return v.value
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) Set(val *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations(val *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations {
	return &NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations{value: val, isSet: true}
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsLocations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


