/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ToNewSubscribers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToNewSubscribers{}

// ToNewSubscribers Determines if the campaign qualifies to be resent to new subscribers.
type ToNewSubscribers struct {
	// Determines if the campaign qualifies to be resent to this segment.
	IsEligible *bool `json:"is_eligible,omitempty"`
	// The reason the campaign is not eligible to be resent to this segment.
	Reason *string `json:"reason,omitempty"`
}

// NewToNewSubscribers instantiates a new ToNewSubscribers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToNewSubscribers() *ToNewSubscribers {
	this := ToNewSubscribers{}
	return &this
}

// NewToNewSubscribersWithDefaults instantiates a new ToNewSubscribers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToNewSubscribersWithDefaults() *ToNewSubscribers {
	this := ToNewSubscribers{}
	return &this
}

// GetIsEligible returns the IsEligible field value if set, zero value otherwise.
func (o *ToNewSubscribers) GetIsEligible() bool {
	if o == nil || IsNil(o.IsEligible) {
		var ret bool
		return ret
	}
	return *o.IsEligible
}

// GetIsEligibleOk returns a tuple with the IsEligible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToNewSubscribers) GetIsEligibleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEligible) {
		return nil, false
	}
	return o.IsEligible, true
}

// HasIsEligible returns a boolean if a field has been set.
func (o *ToNewSubscribers) HasIsEligible() bool {
	if o != nil && !IsNil(o.IsEligible) {
		return true
	}

	return false
}

// SetIsEligible gets a reference to the given bool and assigns it to the IsEligible field.
func (o *ToNewSubscribers) SetIsEligible(v bool) {
	o.IsEligible = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ToNewSubscribers) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ToNewSubscribers) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ToNewSubscribers) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ToNewSubscribers) SetReason(v string) {
	o.Reason = &v
}

func (o ToNewSubscribers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToNewSubscribers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEligible) {
		toSerialize["is_eligible"] = o.IsEligible
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableToNewSubscribers struct {
	value *ToNewSubscribers
	isSet bool
}

func (v NullableToNewSubscribers) Get() *ToNewSubscribers {
	return v.value
}

func (v *NullableToNewSubscribers) Set(val *ToNewSubscribers) {
	v.value = val
	v.isSet = true
}

func (v NullableToNewSubscribers) IsSet() bool {
	return v.isSet
}

func (v *NullableToNewSubscribers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToNewSubscribers(val *ToNewSubscribers) *NullableToNewSubscribers {
	return &NullableToNewSubscribers{value: val, isSet: true}
}

func (v NullableToNewSubscribers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToNewSubscribers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


