/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetReportingFacebookAds200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReportingFacebookAds200Response{}

// GetReportingFacebookAds200Response A collection of Facebook ads.
type GetReportingFacebookAds200Response struct {
	FacebookAds []GetReportingFacebookAds200ResponseFacebookAdsInner `json:"facebook_ads,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems *int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}

// NewGetReportingFacebookAds200Response instantiates a new GetReportingFacebookAds200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReportingFacebookAds200Response() *GetReportingFacebookAds200Response {
	this := GetReportingFacebookAds200Response{}
	return &this
}

// NewGetReportingFacebookAds200ResponseWithDefaults instantiates a new GetReportingFacebookAds200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReportingFacebookAds200ResponseWithDefaults() *GetReportingFacebookAds200Response {
	this := GetReportingFacebookAds200Response{}
	return &this
}

// GetFacebookAds returns the FacebookAds field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200Response) GetFacebookAds() []GetReportingFacebookAds200ResponseFacebookAdsInner {
	if o == nil || IsNil(o.FacebookAds) {
		var ret []GetReportingFacebookAds200ResponseFacebookAdsInner
		return ret
	}
	return o.FacebookAds
}

// GetFacebookAdsOk returns a tuple with the FacebookAds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200Response) GetFacebookAdsOk() ([]GetReportingFacebookAds200ResponseFacebookAdsInner, bool) {
	if o == nil || IsNil(o.FacebookAds) {
		return nil, false
	}
	return o.FacebookAds, true
}

// HasFacebookAds returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200Response) HasFacebookAds() bool {
	if o != nil && !IsNil(o.FacebookAds) {
		return true
	}

	return false
}

// SetFacebookAds gets a reference to the given []GetReportingFacebookAds200ResponseFacebookAdsInner and assigns it to the FacebookAds field.
func (o *GetReportingFacebookAds200Response) SetFacebookAds(v []GetReportingFacebookAds200ResponseFacebookAdsInner) {
	o.FacebookAds = v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200Response) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200Response) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200Response) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *GetReportingFacebookAds200Response) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetReportingFacebookAds200Response) GetLinks() []ResourceLink {
	if o == nil || IsNil(o.Links) {
		var ret []ResourceLink
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportingFacebookAds200Response) GetLinksOk() ([]ResourceLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetReportingFacebookAds200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []ResourceLink and assigns it to the Links field.
func (o *GetReportingFacebookAds200Response) SetLinks(v []ResourceLink) {
	o.Links = v
}

func (o GetReportingFacebookAds200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReportingFacebookAds200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FacebookAds) {
		toSerialize["facebook_ads"] = o.FacebookAds
	}
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGetReportingFacebookAds200Response struct {
	value *GetReportingFacebookAds200Response
	isSet bool
}

func (v NullableGetReportingFacebookAds200Response) Get() *GetReportingFacebookAds200Response {
	return v.value
}

func (v *NullableGetReportingFacebookAds200Response) Set(val *GetReportingFacebookAds200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReportingFacebookAds200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReportingFacebookAds200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReportingFacebookAds200Response(val *GetReportingFacebookAds200Response) *NullableGetReportingFacebookAds200Response {
	return &NullableGetReportingFacebookAds200Response{value: val, isSet: true}
}

func (v NullableGetReportingFacebookAds200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReportingFacebookAds200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


