/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner{}

// GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner struct for GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner
type GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner struct {
	Name *string `json:"name,omitempty"`
}

// NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner instantiates a new GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner {
	this := GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner{}
	return &this
}

// NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInnerWithDefaults instantiates a new GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInnerWithDefaults() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner {
	this := GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) SetName(v string) {
	o.Name = &v
}

func (o GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner struct {
	value *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner
	isSet bool
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) Get() *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner {
	return v.value
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) Set(val *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner(val *GetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner {
	return &NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner{value: val, isSet: true}
}

func (v NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllFacebookAds200ResponseFacebookAdsInnerAllOfAudienceTargetingSpecsInterestsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


